services:
  - type: web
    name: Nexbrief-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://nexbrief.vercel.app
      - key: PORT
        value: 3000 